/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function BuzzPlaque(props) {
  const { nodes, materials } = useGLTF("/models/BuzzPlaque.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.baked_mesh001.geometry}
        material={materials["g0.001"]}
        rotation={[0, 0.26, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/BuzzPlaque.gltf");

export default BuzzPlaque;