/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// This a the Three.js component utilized for the Emerging Tech Team page. You can create a js file just like this for another .gltf or .glb file
// here: https://gltf.pmnd.rs/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Football(props) {
  const { nodes, materials } = useGLTF("/models/football.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.baked_mesh001.geometry}
        material={materials["g0.003"]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/football.gltf");

export default Football;