/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// This a the Three.js component utilized for the Emerging Tech Team page. You can create a js file just like this for another .gltf or .glb file
// here: https://gltf.pmnd.rs/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function Map(props) {
  const { nodes, materials } = useGLTF("/models/GTMap.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Ground_-_Plane_"].geometry}
        material={materials["Material.001"]}
        position={[0, -0.5, 0]}
        scale={[1000, 1, 1000]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_1.geometry}
        material={materials.wall}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_1_1.geometry}
        material={materials.roof}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_1_2.geometry}
        material={materials.grey}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_vegetation.geometry}
        material={materials.vegetation}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_forest.geometry}
        material={materials.forest}
        position={[0, 0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_roads_motorway.geometry}
        material={materials.roads_motorway}
        position={[0, 0.3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_roads_residential.geometry}
        material={materials.roads_residential}
        position={[0, 0.3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_roads_tertiary.geometry}
        material={materials.roads_tertiary}
        position={[0, 0.3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_roads_pedestrian.geometry}
        material={materials.roads_pedestrian}
        position={[0, 0.3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_roads_trunk.geometry}
        material={materials.roads_trunk}
        position={[0, 0.3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_roads_secondary.geometry}
        material={materials.roads_secondary}
        position={[0, 0.3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_paths_footway.geometry}
        material={materials.paths_footway}
        position={[0, 0.3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_roads_unclassified.geometry}
        material={materials.roads_unclassified}
        position={[0, 0.3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_roads_primary.geometry}
        material={materials.roads_primary}
        position={[0, 0.3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_roads_service.geometry}
        material={materials.roads_service}
        position={[0, 0.3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_paths_steps.geometry}
        material={materials.paths_steps}
        position={[0, 0.3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_paths_cycleway.geometry}
        material={materials.paths_cycleway}
        position={[0, 0.3, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_areas_pedestrian.geometry}
        material={materials.areas_pedestrian}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4osm_roads_track.geometry}
        material={materials.roads_track}
        position={[0, 0.3, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/GTMap.gltf");

export default Map;