/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function Model(props) {
  const { nodes, materials } = useGLTF("/models/RightConverse.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.baked_mesh001.geometry}
        material={materials["g0.002"]}
        position={[0, 0.16, 0]}
        rotation={[1.63, 0.01, -0.02]}
      />
    </group>
  );
}

useGLTF.preload("/models/RightConverse.glb");

export default Model;