/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// This a the Three.js component utilized for the Emerging Tech Team page. You can create a js file just like this for another .gltf or .glb file
// here: https://gltf.pmnd.rs/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import myModel from "../../models/RightConverse.glb"


function Model(props) {
  const { nodes, materials } = useGLTF(myModel);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.baked_mesh001.geometry}
        material={materials["g0.002"]}
        position={[0, 0.16, 0]}
        rotation={[1.63, 0.01, -0.02]}
      />
    </group>
  );
}

useGLTF.preload(myModel);

export default Model;