/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// This a the Three.js component utilized for the Emerging Tech Team page. You can create a js file just like this for another .gltf or .glb file
// here: https://gltf.pmnd.rs/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function Sweater(props) {
  const { nodes, materials } = useGLTF("/models/t_sweater.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.06, 1.3, -0.02]} rotation={[Math.PI / 2, 0, -2.03]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_lowpoly_1.geometry}
          material={materials.material0000}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_lowpoly_2.geometry}
          material={materials.material0001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_lowpoly_3.geometry}
          material={materials.material0002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_lowpoly_4.geometry}
          material={materials.material0003}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_lowpoly_5.geometry}
          material={materials.material0004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_lowpoly_6.geometry}
          material={materials.material0005}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_lowpoly_7.geometry}
          material={materials.material0006}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh_lowpoly_8.geometry}
          material={materials.material0007}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/t_sweater.glb");

export default Sweater;