# Sample workflow for building and deploying a Gatsby site to GitHub Pages
#
# To get started with Gatsby see: https://www.gatsbyjs.com/docs/quick-start/
#
name: Deploy Gatsby site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Runs on pull requests to generate the deployment preview
  pull_request:
    types: [opened, synchronize, reopened]

  # Allows you to run the workflow manually from Actions
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to Deploy?'
        required: true
        default: 'master'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# UNCOMMENT IF NECESSARY
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
        with:
          # Automatically inject pathPrefix in your Gatsby configuration file.
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: gatsby
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('**/package-lock.json', '**/gatsby-config.js') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      - name: Install dependencies
        run: npm install
      - name: Install parcel watcher
        run: npm install @parcel/watcher
      - name: Rebuild dependencies
        run: npm rebuild
      - name: Clear Gatsby cache
        run: npx gatsby clean
      - name: Build Gatsby
        run: npm run build

      - name: Set artifact name
        id: set-artifact
        run: | 
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "name=pr-preview-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            echo "name=main-site" >> $GITHUB_OUTPUT
          fi
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
          name: ${{ steps.set-artifact.outputs.name }}

  # Deployment job
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy main branch
        id: deployment
        uses: actions/deploy-pages@v4
        with: 
          artifact_name: main-site

  deploy-preview:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Preview to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with: 
          artifact_name: pr-preview-${{ github.event.pull_request.number }}

  cleanup-preview:
    runs-on: ubuntu-latest
    needs: deploy-preview
    if: github.event.pull_request.merged == true || github.event.pull_request.state == 'closed'

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove PR Preview folder
        run: |
          git rm -r --ignore-unmatch previews/pr-${{ github.event.pull_request.number }}
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Cleanup preview for PR #${{ github.event.pull_request.number }}"
          git push
