name: Deploy on Drupal Content Update

on:
  repository_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install -g gatsby-cli
          npm ci  # Regular install
          npm rebuild lmdb --update-binary  # Force rebuild LMDB
          npm rebuild @parcel/watcher --update-binary  # Also rebuild Parcel watcher
      
      - name: Build
        run: |
          echo "Drupal content was updated! Rebuilding static site..."
          npm run deploy
