name: Deploy on Drupal Content Update

on:
  repository_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install -g gatsby-cli
          npm ci --ignore-scripts  # First install without native builds
          npm rebuild @parcel/watcher --update-binary  # Force rebuild
      
      - name: Build
        run: |
          echo "Drupal content was updated! Rebuilding static site..."
          npm run deploy
