name: Deploy on Drupal Content Update
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  repository_dispatch:
    types: [drupal-update]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use a compatible Node.js version for Gatsby

      - name: Install dependencies
        run: npm ci

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@2.12.34

      - name: Deploy
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy

      - name: Trigger notification
        run: |
          curl -X POST \
          -H "Authorization: token ${GH_TOKEN}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"gh-pages-updated"}'
