name: Trigger Plesk on Push to Main

on:
  repository_dispatch:
    types: [gh-pages-updated]

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST to Plesk Webhook
        run: |
          curl -X POST \
            "https://web-plesk57.oit.gatech.edu:8443/modules/git/public/web-hook.php?uuid=d71883be-a513-6f80-308d-86c9c8fb5fec" \
            -H "Content-Type: application/json" \
            -d '{
              "event": "${{ github.event_name }}",
              "repository": "${{ github.repository }}",
              "commit": "${{ github.sha }}",
              "ref": "${{ github.ref }}",
              "sender": "${{ github.actor }}"
            }'
