name: Trigger Plesk on Push to Main

on:
  repository_dispatch:
    types: [gh-pages-updated]

jobs:
  notify-plesk:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Plesk Webhook via Dedicated Action
        uses: distributhor/workflow-webhook@v2
        with:
          webhook_url: "https://web-plesk57.oit.gatech.edu:8443/modules/git/public/web-hook.php?uuid=d71883be-a513-6f80-308d-86c9c8fb5fec"
          data: |
            {
              "event": "${{ github.event_name }}",
              "repo": "${{ github.repository }}",
              "commit": "${{ github.sha }}"
            }
          headers: '{"Content-Type": "application/json"}'
